apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: artifactory
  spec:
    params:
      - name: url
        value: https://github.com/oiricaud/devops-demo-kabanero-pipelines
    type: git
kind: List