apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app-ibmcloud-task
  namespace: kabanero
  author: Oscar Ricaud
  date: 05/26/20
spec:
  inputs:
    params:
      - name: docker_image
        description: The image that we are using for this project which includes the binaries for oc, kubectl, cf, apic, ibm cli, git, curl, tree
        default: ""
      - name: cf_org
        description: Specify the Cloud Foundry org to run in.
        default: ""
      - name: cf_space
        description: Specify the Cloud Foundry space to run in.
        default: ""
      - name: cf_app_name
        description: What to name the application on Cloud Foundry.
        default: ""
    resources:
      - name: source
        type: git
  steps:
    - name: deploying-app
      image: $(inputs.params.docker_image)
      command: ["/bin/sh"]
      args:
        - -c
        - |
          set -euxo pipefail
          
          # Login with the api key
          ibmcloud login --apikey ${ibmcloud_api_token} -r us-south
        
          # install ibm cloud
          ibmcloud cf install
          
          # Set resource group, cf org and space
          ibmcloud target -g ${cf_org} -o ${cf_org} -s ${cf_space}

          # Change directory to the clone app
          # cd devops-demo-storefront-ui

          # Push app to cloud foundry
          ibmcloud cf push -f ./manifest.yml ${cf_app_name}

      env:
        - name: cf_org
          value: $(inputs.params.cf_org)
        - name: cf_space
          value: $(inputs.params.cf_space)
        - name: cf_app_name
          value: $(inputs.params.cf_app_name)
        - name: ibmcloud_api_token
          valueFrom:
            secretKeyRef:
              name: ibmc-access
              key: TOKEN
      resources: {}
      workingDir: $(inputs.resources.source.path)
