apiVersion: v1
data:
  ARTIFACTORY_ENCRYPT: ""
kind: Secret
metadata:
  annotations:
    description: Secret to hold the username and password for artifactory so that
      other components can access it
  labels:
    app: artifactory
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: artifactory
    app.kubernetes.io/name: artifactory
    app.kubernetes.io/part-of: artifactory
    app.kubernetes.io/version: 0.1.3
    chart: tool-config-0.1.3
    group: catalyst-tools
    grouping: garage-cloud-native-toolkit
    release: artifactory
  name: artifactory-access
type: Opaque