apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: git-package-release-update-pl-pullrequest-binding
  namespace: tekton-pipelines
  author: Oscar I. Ricaud
  date: 04/21/20
spec:
  params:
    - name: gitrevision
      value: $(body.pull_request_review.head.sha)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)    
    - name: docker-tag
      value: '$(body.repository.name):$(body.pull_request_review.head.sha)'
    - name: event-type
      value: $(header.X-Github-Event)
    - name: webhooks-tekton-git-branch
      value: $(body.webhooks-tekton-git-branch)